appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: IvlJDFx7k6Zv8HbVifd6fm1Ar9JWZOQAMfpfQJXLcUJU4zHSJu/exvEMXqciko9FBGp8ldH19kZ0Qx9fCEB+Dor7pUbdDXXol6nfQd9i1MkN6tvoOUykW/aZ1jOUmRGxAkJPuj/0MribouJaS0P0Kr92zAaIKiLvJDthaDHGIybm7jp9ZDN8RJTmdZp5/JQH3mqd7Ykt/7O1wfOPg2Wqec3Q+W+FyGxLF+EAOId59aj2V0ocGK5j7sIQC4kqyG3gTgw4SIyCXTUJfEmTuLx4uJqsbHH/gO3WiDxFnD+5b3YDmn6efKwcbir7BkI8KHasfW9zBwOeGFYK2jMaGaUukhI//Wu770TzQpXiZiwrHGMfkzHmZeu86Hzife6iV1vscI3hOk2yIT6kY57I/ZFj6mStSF5SzDJYguBmr68LVoE1gPwEagsw0fO6OpCCNV/keQBkXFW7PIsypF3L36jXWE21S6N+/WmwxjquaFrBtnwCtxb/jOiJIupDYDQcOSxUDEGv/DrhZAxCsTFRPi/sMB3JHL6Nm95eF0J3cUZRT51pX8PoYYRcIRTv2fbgds7Asf1JereS/ksmPCNVovxbimdhGG0EFb6Rg+47uydOh2kBG+tDHNYdgfGjnZfhZH+DEeoH1hX2sxTATdmciASHOYduBS/hCwqr2ufuzAt+xZA=
